import argparse
import csv
import json
from collections import defaultdict, deque

EPS = 1e-12


# --------------------------------------------------
# Helpers: parse pynauty.autgrp(...)
# --------------------------------------------------

def _extract_orbit_ids_from_autgrp_result(result):
    if not isinstance(result, (tuple, list)) or len(result) == 0:
        raise TypeError(f"autgrp returned unexpected: {type(result)} {result!r}")

    last = result[-1]

    if isinstance(last, int):
        if len(result) < 2:
            raise TypeError(f"autgrp malformed: {result!r}")
        orbit_ids = result[-2]
    else:
        orbit_ids = last

    if isinstance(orbit_ids, int):
        raise TypeError(f"orbit_ids malformed: {result!r}")

    return orbit_ids


def _extract_generators_from_autgrp_result(result, total_vertices):
    """
    Expect result[0] to contain permutations.
    Keep only objects that are valid permutations of 0..total_vertices-1.
    """
    if not isinstance(result, (tuple, list)) or len(result) == 0:
        raise TypeError(f"autgrp returned unexpected: {type(result)} {result!r}")

    first = result[0]
    if not isinstance(first, (tuple, list)):
        raise TypeError(f"autgrp generators malformed: {result!r}")

    gens = []
    for g in first:
        if not isinstance(g, (tuple, list)):
            continue
        if len(g) != total_vertices:
            continue

        perm = [int(x) for x in g]
        if sorted(perm) != list(range(total_vertices)):
            continue
        gens.append(perm)

    return gens


# --------------------------------------------------
# Build current coverage graph
# --------------------------------------------------

def _build_coverage_graph(inst, radius, candidates, active_demands):
    candidates = sorted(candidates)
    active_demands = sorted(active_demands)

    nC = len(candidates)
    nD = len(active_demands)
    total_vertices = nC + nD

    center_index = {c: i for i, c in enumerate(candidates)}
    demand_index = {u: i for i, u in enumerate(active_demands)}

    adj = {i: [] for i in range(total_vertices)}

    for c in candidates:
        ci = center_index[c]
        row = inst.dist[c]
        for u in active_demands:
            if row[u] <= radius + EPS:
                ui = nC + demand_index[u]
                adj[ci].append(ui)
                adj[ui].append(ci)

    coloring = []
    if nC > 0:
        coloring.append(set(range(0, nC)))
    if nD > 0:
        coloring.append(set(range(nC, nC + nD)))

    return candidates, active_demands, nC, nD, total_vertices, adj, coloring


# --------------------------------------------------
# Group/orbits on center positions
# --------------------------------------------------

def _compose_perm(p, q):
    """
    Compose permutations in image notation:
      r = p o q
      r[i] = p[q[i]]
    """
    return tuple(p[q[i]] for i in range(len(p)))


def _generate_full_group_from_generators(n, generators):
    """
    Return the full subgroup of S_n generated by `generators`.
    Each generator is a permutation in image notation on {0,...,n-1}.
    """
    identity = tuple(range(n))
    if n == 0:
        return [identity]

    gens = [tuple(g) for g in generators if tuple(g) != identity]
    if not gens:
        return [identity]

    seen = {identity}
    q = deque([identity])

    while q:
        cur = q.popleft()
        for g in gens:
            nxt = _compose_perm(g, cur)
            if nxt not in seen:
                seen.add(nxt)
                q.append(nxt)

    return sorted(seen)


def compute_center_group(
    inst,
    radius,
    candidates,
    active_demands,
):
    import pynauty

    candidates, active_demands, nC, nD, total_vertices, adj, coloring = _build_coverage_graph(
        inst, radius, candidates, active_demands
    )

    if total_vertices == 0:
        return candidates, [], [], [tuple()]

    g = pynauty.Graph(
        number_of_vertices=total_vertices,
        adjacency_dict=adj,
        vertex_coloring=coloring,
    )

    result = pynauty.autgrp(g)

    # Orbits on centers
    orbit_ids = _extract_orbit_ids_from_autgrp_result(result)
    orbit_dict = defaultdict(list)
    for v, oid in enumerate(orbit_ids):
        orbit_dict[oid].append(v)

    auto_classes = []
    for orbit in orbit_dict.values():
        centers = [candidates[v] for v in orbit if v < nC]
        if len(centers) >= 2:
            auto_classes.append(sorted(centers))
    auto_classes.sort()

    # Generators restricted to center block
    raw_gens = _extract_generators_from_autgrp_result(result, total_vertices)

    center_gens = []
    seen = set()
    identity = tuple(range(nC))

    for perm in raw_gens:
        cperm = []
        ok = True
        for i in range(nC):
            img = perm[i]
            if not (0 <= img < nC):
                ok = False
                break
            cperm.append(img)

        if not ok:
            continue

        tpl = tuple(cperm)
        if tpl == identity:
            continue
        if tpl in seen:
            continue

        seen.add(tpl)
        center_gens.append(tpl)

    if nC > 0 and not center_gens and auto_classes:
        raise RuntimeError(
            "No nontrivial center generators parsed from pynauty.autgrp(...), "
            "but nontrivial center orbits exist. Check autgrp output format."
        )

    full_group = _generate_full_group_from_generators(nC, center_gens)

    return candidates, auto_classes, center_gens, full_group


# --------------------------------------------------
# Full lex-leader encoding
# --------------------------------------------------

def _new_var(cnf):
    v = max(getattr(cnf, "nv", 0), 0) + 1
    cnf.nv = v
    return v


def _add_equiv_same_bit(cnf, z, x, y):
    # z <-> (x == y)
    cnf.append([-z, -x, y])
    cnf.append([-z, x, -y])
    cnf.append([-x, -y, z])
    cnf.append([x, y, z])


def _add_equiv_prefix_and_same(cnf, z, prev_eq, x, y):
    # z <-> (prev_eq AND (x == y))
    cnf.append([-z, prev_eq])
    cnf.append([-z, -x, y])
    cnf.append([-z, x, -y])
    cnf.append([-prev_eq, -x, -y, z])
    cnf.append([-prev_eq, x, y, z])


def add_lex_leader_geq_clause_system(cnf, xs, ys):
    """
    Add CNF for:
        xs >=_lex ys
    with Boolean order 1 > 0.
    """
    m = len(xs)
    if m != len(ys):
        raise ValueError("xs and ys must have same length")
    if m == 0:
        return

    eq = []

    for i in range(m):
        x = xs[i]
        y = ys[i]

        # If prefix equal so far, then x >= y
        if i == 0:
            cnf.append([x, -y])
        else:
            cnf.append([-eq[i - 1], x, -y])

        # Build prefix equality variable for next step
        if i < m - 1:
            z = _new_var(cnf)
            if i == 0:
                _add_equiv_same_bit(cnf, z, x, y)
            else:
                _add_equiv_prefix_and_same(cnf, z, eq[i - 1], x, y)
            eq.append(z)


def add_lex_leader_for_permutation(
    inst,
    cnf,
    candidates_sorted,
    center_perm,
):
    """
    Add:
        X >=_lex pi(X)

    where X is the y-vector over candidates_sorted, and center_perm is a
    permutation on center positions in image notation:
        center_perm[i] = image of position i
    """
    nC = len(candidates_sorted)
    if nC == 0:
        return

    inv = [0] * nC
    for i, j in enumerate(center_perm):
        inv[j] = i

    xs = [inst.y_lit_all[c] for c in candidates_sorted]
    ys = [inst.y_lit_all[candidates_sorted[inv_pos]] for inv_pos in inv]

    add_lex_leader_geq_clause_system(cnf, xs, ys)


# --------------------------------------------------
# Public API: TRUE full lex-leader on the full group
# --------------------------------------------------

def automorphism_full_full_lex_leader_symmetry_breaking(
    inst,
    cnf,
    radius,
    candidates,
    active_demands,
    verbose=False,
    max_group_size=None,
):
    """
    TRUE full lex-leader:
      - compute the full permutation group on center positions
      - for every non-identity permutation pi in the group,
        add X >=_lex pi(X)

    Warning: group size may blow up quickly.
    """
    candidates_sorted, orbits, center_gens, full_group = compute_center_group(
        inst=inst,
        radius=radius,
        candidates=candidates,
        active_demands=active_demands,
    )

    identity = tuple(range(len(candidates_sorted)))
    nontrivial_group = [g for g in full_group if g != identity]

    if max_group_size is not None and len(full_group) > max_group_size:
        raise RuntimeError(
            f"Full automorphism group too large: |G|={len(full_group)} "
            f"> max_group_size={max_group_size}"
        )

    if verbose:
        print(
            f"[SB-FULL-FULL] generators={len(center_gens)} "
            f"group_size={len(full_group)} "
            f"nontrivial={len(nontrivial_group)} "
            f"orbits={len(orbits)} "
            f"candidates={len(candidates_sorted)}"
        )

    for perm in nontrivial_group:
        add_lex_leader_for_permutation(
            inst=inst,
            cnf=cnf,
            candidates_sorted=candidates_sorted,
            center_perm=perm,
        )


# --------------------------------------------------
# Analysis CLI
# --------------------------------------------------

def load_instance_and_seed_radius(inst_desc):
    from experiments import load_instance
    inst, seed_idx = load_instance(inst_desc)
    radius = inst.radii[seed_idx]
    return inst, radius


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--instances", required=True)
    parser.add_argument("--out-prefix", default="symmetry_full_full")
    parser.add_argument(
        "--max-group-size",
        type=int,
        default=None,
        help="Optional safeguard for full group expansion",
    )
    args = parser.parse_args()

    with open(args.instances, "r", encoding="utf-8") as f:
        data = json.load(f)

    summary_rows = []
    detail_rows = []

    for inst_desc in data:
        name = inst_desc["name"]
        p = inst_desc["p"]

        print(f"[PROCESS] {name}, p={p}")

        inst, radius = load_instance_and_seed_radius(inst_desc)
        print(f"  mapped radius = {radius}")

        candidates = list(range(inst.n))
        active_demands = list(range(inst.n))

        candidates_sorted, auto_classes, center_gens, full_group = compute_center_group(
            inst=inst,
            radius=radius,
            candidates=candidates,
            active_demands=active_demands,
        )

        if args.max_group_size is not None and len(full_group) > args.max_group_size:
            raise RuntimeError(
                f"{name}: |G|={len(full_group)} > max_group_size={args.max_group_size}"
            )

        total_auto_nodes = sum(len(c) for c in auto_classes)
        max_auto_class = max((len(c) for c in auto_classes), default=0)
        num_auto_classes = len(auto_classes)
        auto_ratio = (
            (total_auto_nodes / len(candidates_sorted))
            if len(candidates_sorted) > 0 else 0.0
        )

        summary_rows.append({
            "instance": name,
            "p": p,
            "radius_used": radius,
            "symmetry_type": "automorphism_full_full_lex",
            "num_candidates": len(candidates_sorted),
            "num_demands": len(active_demands),
            "num_symmetry_classes": num_auto_classes,
            "total_symmetric_nodes": total_auto_nodes,
            "max_class_size": max_auto_class,
            "num_generators": len(center_gens),
            "group_size": len(full_group),
            "num_nonidentity_perms": max(0, len(full_group) - 1),
            "symmetry_ratio": auto_ratio,
        })

        for idx, centers in enumerate(auto_classes, start=1):
            detail_rows.append({
                "instance": name,
                "p": p,
                "radius_used": radius,
                "symmetry_type": "automorphism_full_full_lex",
                "class_id": idx,
                "class_size": len(centers),
                "centers": " ".join(map(str, centers)),
            })

    if summary_rows:
        summary_path = f"{args.out_prefix}_summary.csv"
        with open(summary_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(summary_rows[0].keys()))
            writer.writeheader()
            writer.writerows(summary_rows)
    else:
        summary_path = None

    if detail_rows:
        detail_path = f"{args.out_prefix}_details.csv"
        with open(detail_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(detail_rows[0].keys()))
            writer.writeheader()
            writer.writerows(detail_rows)
    else:
        detail_path = None

    print("[DONE]")
    if summary_path:
        print("  ", summary_path)
    if detail_path:
        print("  ", detail_path)


if __name__ == "__main__":
    main()